### ISSUE TITLE
[Backend] As a User, after my keywords have been uploaded, they should be processed immediately

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#10]
## Why

Keywords after successfully uploaded should be processed immediately

## Acceptance Criteria

- Keywords after persisted in the database should be processed immediately via background job
- The processing pipeline concurrency must be constraints
- Retry mechanism should be implemented
- Should have test cases

## Implementation Details
- Use Sidekiq for background job processing
- After a keyword is successfully processed, users should be notified about such events. However, this issue won't cover it
- After too many failed attempts, a keyword should be mark as permanently failed. Users should be notified about such events. However, this issue won't cover it

**Comment by olivierobert** [comment]
This story is way too large. It is the core business logic. I recommend the following split:

- Set up Sidekiq for background (chore)
- [Backend] Scrape data from the Google Serch page (feature ) -> implementing the scraper logic
- [Backend] As a user, my uploaded keywords are processed immediately (feature) -> integration the background job and scraper
- [UI] As a user, my uploaded keywords are processed immediately (feature) -> Show a message to the user, show scraping status, etc.

**Comment by Goose97** [comment]
Split into smaller issues: #13 #14 #15 #16
