### ISSUE TITLE
[Backend] As a User, I can view the list of my uploaded keywords

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#11]
Backend for #12 

## Why

Users should be able to view their uploaded keywords list

## Acceptance Criteria

- Users should be able to view the list of uploaded keywords

## Notes
- The response will not (yet) contains information about scarping results. These information will be added later once we implement the keyword processing logic

**Comment by andyduong1920** [comment]
@Goose97 I would recommend to separate the `Backend - Web version` ticket and the `API` ticket, we will have 3 tickets
- [Backend] As a User, I can view the list of my uploaded keywords
- [UI] As a User, I can view the list of my uploaded keywords
- [API] As a User, I can view the list of my uploaded keywords

Same for other API endpoints
