### ISSUE TITLE
[UI] As a User, I can view the list of my uploaded keywords

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#12]
Frontend for #11 

## Why

Users should be able to view their uploaded keywords list

## Acceptance Criteria

- Provide a function interface
- The UI should be able to view multiple keywords at once (use table layout, preferably)
- The UI should implement pagination
- The UI should support sort by keyword feature (optional)

**Comment by andyduong1920** [comment]
Should we add the `[Optional]` prefix into the `The UI should support sort by keyword feature` AC as it's not mandatory and the IC does not requires it @Goose97?
