### ISSUE TITLE
[Chore] Set up Sidekiq for background job

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#13]
## Why

A background job system provides us a better control of how we should process user's keywords (concurrency control, job persistency, ...)

## Acceptance Criteria

- Can enqueue to Sidekiq
- Can dequeue to Sidekiq
- Sidekiq MUST provides persistency, meaning if Sidekiq crashes, we won't lose any ongoing jobs

**Comment by andyduong1920** [comment]
We already have sidekiq setup, I would recommend to change this ticket title to 

- [Backend] As a user, my upload keyword should be processed in background

**Comment by Goose97** [comment]
#15 should cover this. I'll close this issue
