### ISSUE TITLE
[UI] As a User, my uploaded keywords are processed immediately

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#16]
## Why

Processing upload keywords immediately provides a smooth and snappier interface, enhances the application UX

## Acceptance Criteria

- After upload a file successfully, the UI is updated to reflect the new scraping job
- While the file is processed, the UI is updated in real-time to reflect the current status. For each keyword, it should display:
  - The current status: pending / processing / succeeded / failed
  - A link to see details information once the scraping succeeds

## Notes
- ~~`retry keywords` are keywords which have failed to scrape and have been scheduled for retry~~ (We don't support retry status for now). `error keywords` are keywords which have exceeded the maximum retry times. See #15 for more details

**Comment by andyduong1920** [comment]
Hi @Goose97 for the `real time` feature, it should be an Advance feature, I would suggest to de priority that advance feature and you can add it when we have all AC required features, what do you think?

**Comment by olivierobert** [comment]
@Goose97 I have reworked the title for this user story to use the proper active voice, i.e., avoid using "should" as it is obsolete and not in sync with modern product management practices.
