### ISSUE TITLE
[Backend] As a User, I can sign up with username and password

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#4]
Backend for #5 

## Why
The application requires user authentication to correctly separate data between different users. To achieve that, users must have a way to register themselves to the application.

## Acceptance Criteria
- Users must be able to register an account
- Upon successful registration, users should be directed to the dashboard page
- Upon unsuccessful registration, users should be notify with the failure reason

**Comment by andyduong1920** [comment]
This 4 tickets LGTM @Goose97 



![Image](https://github.com/Goose97/google-scraper-ruby/assets/11751745/15aa0608-ed55-43a5-ba69-08006d204fab)
