### ISSUE TITLE
[UI] As a User, I can sign up with username and password

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#5]
Frontend for #4 

## Why
The application requires user authentication to correctly separate data between different users. To achieve that, users must have a way to register themselves to the application.

## Acceptance Criteria

- Implement a form with two attributes: `email` and `password`
- Enable the submit button only if both inputs are filled (optional)
- Show validation error in case of authentication error.

**Comment by olivierobert** [comment]
The Acceptance Criteria (AC) do not say much 🙈 Prefer describing the UI (it can give you some ideas for the implementation):

```
- Implement a form with two attributes: `email` and `password`
- Enable the submit button only if noth inputs are filled (optional)
- Show validation error in case of authentication error.
```

> **Note**
> It would be best to use email instead of username as with Devise (the gem used for authentication), the email will be needed to confirm a user's creation
