### ISSUE TITLE
[Backend] As a User, I can upload CSV keyword files

### ISSUE THREAD

**Issue by Goose97** [Goose97/google-scraper-ruby#9]
Backend for #8 

## Why

Authenticated users should be able to provide keywords to scrape. To achieve that, we provide an interface for users to upload CSV files.

## Acceptance Criteria

- Authenticated users must be able to upload CSV files containing keywords
- Keyword files should be validated:
  - A keyword file must contains between 1 and 1000 keywords
  - A keyword file must have size limit of 5MB
- After upload, all keywords in the file should be persisted in the database
- Do NOT process the keyword file. This will tackled in #10

**Comment by olivierobert** [comment]
The note should be part of the ACs (also tests must be added by default so they can be skipped):

```
- Authenticated users must be able to upload CSV files containing keywords
- Validate the keyword file:
   - A keyword file must contains between 1 and 1000 keywords
   - A keyword file must have size limit of 5MB
- After upload, all keywords in the file should be persisted in the - 
- Do NOT process the keyword file. This will tackled in #10.
```

ACs can contain both what to do and what NOT to do (see the emphasis on the NOT for readability).
